const DELETE_BLANK_LINES = 1;
const INSERT_INDENT = 2;
const DELETE_SPACE_IN_CHINESE_CHARACTER = 3;
const INSERT_SPACE_IN_CHINESE_AND_ENGLISH = 4;
const DELETE_SPACE_IBETWEEN_CHINESE_CHARACTERS_AND_CHINESE_PUNCTUATIONS = 5;

const FIX_COMMA = 101;
const FIX_DOT = 102;
const FIX_DOTS_TO_ELLIPSIS = 103;
const FIX_COLON = 104;
const FIX_BANG = 105;
const FIX_QUESTION_MARK = 106;
const FIX_SEMICOLON = 107;
const FIX_CHINESE_COMMAS_FOLD = 108;
const FIX_CHINESE_DOTS_FOLD = 109;
const FIX_CHINESE_ELLIPSISES_FOLD = 110;
const FIX_ENGLISH_BRACKETS_TO_CHINESE_BRACKETS = 111;
const FIX_GUILLEMET = 112;
const FIX_CHINESE_DASH = 113;
const FIX_EN_QUOTES_TO_CN_QUOTES = 114;

const INSERT_SPACE_AFTER_PERCENT_SIGN = 201;

export {
  DELETE_BLANK_LINES,
  INSERT_INDENT,
  DELETE_SPACE_IN_CHINESE_CHARACTER,
  INSERT_SPACE_IN_CHINESE_AND_ENGLISH,
  DELETE_SPACE_IBETWEEN_CHINESE_CHARACTERS_AND_CHINESE_PUNCTUATIONS,
  FIX_COMMA,
  FIX_DOT,
  FIX_DOTS_TO_ELLIPSIS,
  FIX_COLON,
  FIX_BANG,
  FIX_QUESTION_MARK,
  FIX_SEMICOLON,
  FIX_CHINESE_COMMAS_FOLD,
  FIX_CHINESE_DOTS_FOLD,
  FIX_CHINESE_ELLIPSISES_FOLD,
  FIX_ENGLISH_BRACKETS_TO_CHINESE_BRACKETS,
  FIX_GUILLEMET,
  FIX_CHINESE_DASH,
  FIX_EN_QUOTES_TO_CN_QUOTES,
  INSERT_SPACE_AFTER_PERCENT_SIGN,
};
