const DELETE_BLANK_LINES: number = 1;
const INSERT_INDENT: number = 2;
const DELETE_SPACE_IN_CHINESE_CHARACTER: number = 3;
const INSERT_SPACE_IN_CHINESE_AND_ENGLISH: number = 4;
const DELETE_SPACE_IBETWEEN_CHINESE_CHARACTERS_AND_CHINESE_PUNCTUATIONS: number = 5;
const FIX_COMMA: number = 101;
const FIX_DOT: number = 102;
const FIX_DOTS_TO_ELLIPSIS: number = 103;
const FIX_COLON: number = 104;
const FIX_BANG: number = 105;
const FIX_QUESTION_MARK: number = 106;
const FIX_SEMICOLON: number = 107;
const FIX_CHINESE_COMMAS_FOLD: number = 108;
const FIX_CHINESE_DOTS_FOLD: number = 109;
const FIX_CHINESE_ELLIPSISES_FOLD: number = 110;
const FIX_ENGLISH_BRACKETS_TO_CHINESE_BRACKETS: number = 111;
const FIX_GUILLEMET: number = 112;
const FIX_CHINESE_DASH: number = 113;
const INSERT_SPACE_AFTER_PERCENT_SIGN: number = 113;

export {
  DELETE_BLANK_LINES,
  INSERT_INDENT,
  DELETE_SPACE_IN_CHINESE_CHARACTER,
  INSERT_SPACE_IN_CHINESE_AND_ENGLISH,
  DELETE_SPACE_IBETWEEN_CHINESE_CHARACTERS_AND_CHINESE_PUNCTUATIONS,
  FIX_COMMA,
  FIX_DOT,
  FIX_DOTS_TO_ELLIPSIS,
  FIX_COLON,
  FIX_BANG,
  FIX_QUESTION_MARK,
  FIX_SEMICOLON,
  FIX_CHINESE_COMMAS_FOLD,
  FIX_CHINESE_DOTS_FOLD,
  FIX_CHINESE_ELLIPSISES_FOLD,
  FIX_ENGLISH_BRACKETS_TO_CHINESE_BRACKETS,
  FIX_GUILLEMET,
  FIX_CHINESE_DASH,
  INSERT_SPACE_AFTER_PERCENT_SIGN,
};
